### ISSUE TITLE
Profiling LAMMPS functions

### ISSUE THREAD

**Issue by rmatsum836** [mosdef-hub/gmso#364]
I'm starting to look at the performance of the LAMMPS writer and reader.  I looked at a tip3p water system with `n` molecules, where `n = [100, 500, 1000, 2000]`.  Comparing `write_lammpsdata` in `mBuild` and `GMSO`, here is what I got:

[times.pdf](https://github.com/mosdef-hub/gmso/files/4361546/times.pdf)

Obviously this performance isn't acceptable, but I'm not quite sure why the performance is so bad in comparison to mBuild.  I'm going to spend some time digging deeper into this.

**Comment by rmatsum836** [comment]
https://gist.github.com/rmatsum836/45f1ac390cd7908a27ea45cb30a59e2a

**Comment by rmatsum836** [comment]
One of the culprits was calling `top.is_typed`.  Adding the argument `updated=True` makes this function significantly faster though.  Will submit a PR

[times.pdf](https://github.com/mosdef-hub/gmso/files/4361968/times.pdf)

**Comment by uppittu11** [comment]
I'll try to summarize what we talked about over Slack so we have it on record here. 

Notebook I used for testing: https://gist.github.com/uppittu11/6789bd71ce77e6d31141626e7c9f6a42

Another major bottleneck in the lammpswriter was calling `top.sites.index(someSite)`. This is because `top.sites` is a tuple, which has slow O(N) lookup.
https://github.com/mosdef-hub/gmso/blob/5781bf8a4917e83cac541a0c5d9343a4d2cbc1f5/gmso/core/topology.py#L227-L229
![image](https://user-images.githubusercontent.com/33552857/77213751-f0e1d180-6ad9-11ea-96a5-fbd7c7304bda.png)


Another option was making top.sites return an indexed set: 
```python3
 @property 
 def sites(self): 
     return IndexedSet(self._sites) 
```

This made lookup twice as fast, but still O(N) since every time type.sites is called, the IndexedSet needs to be rebuilt. 
![image](https://user-images.githubusercontent.com/33552857/77213795-225a9d00-6ada-11ea-8153-db9832b24e4c.png)

Currently we are looking at options for how to improve the output of `top.sites`. 

1. @umesh-timalsina  suggested that we could have a `top.get_site_index(site)` function that would get the index of a site using the internal `top._sites` `IndexedSet` in O(1) time. This can be also be extended to bonds, angles, dihedrals, and impropers. 
2. Another option is to make `top.sites` a generator. Then the burden would be on submodules like the LAMMPS writer to generate a list, tuple, set, dictionary, whatever indexed data structure once at the beginning, which would be used throughout the submodule.

**Comment by rsdefever** [comment]
Can someone help me understand the pros and cons of (1) vs. (2)? IMO the goal should be to handle 100k+ atom systems in < 1 s. Maybe thats overly ambitious.

**Comment by uppittu11** [comment]
@rsdefever, as far as I can tell, both options are equally efficient, but maybe @umesh-timalsina might have some input on this. Ideally someone would try out both options and see if one is any faster than the other, but I guess the choice would just be up to whoever ends up submitting the PR.

**Comment by mattwthompson** [comment]
The primary downside to option 2 is that many operations will require unpacking the generator into a list, which feels kinda clunky to do. But it has the benefit of being more iterate-over-able

**Comment by rsdefever** [comment]
@uppittu11 Actually when I asked the question I was thinking less from an efficiency standpoint and more from usability. But yes if one was much more efficient I would certainly vote for that option.

**Comment by umesh-timalsina** [comment]
@rsdefever https://colab.research.google.com/drive/1eK1m9cUdnWdIR92vaqXycgcACc6RFlCV
Here's a colab notebook that compares lookup times for every datastructure @uppittu11 has indicated. 
We should implement both of them as convenience methods to be used at discretion and need of the current scope. If your needs are just indexing (having a method like `site_index` gives the best way to handle this) and returning an `IndexedSet` on property would be redundant when using this. Having a generator gives programmer more flexibility because you could create a data structure that would best suit your needs in the current scope of code.
