### ISSUE TITLE
Pydantic new release (v1.7) 

### ISSUE THREAD

**Issue by daico007** [mosdef-hub/gmso#481]
Pydantic just had a huge release yesterday (https://github.com/samuelcolvin/pydantic/releases) and our tests on master is failing. We need to either pin pydantic to the previous version (1.6.1) or dive in and find the bugs.

**Comment by umesh-timalsina** [comment]
The issue is that `smart_deep_copy` function doesn't take into account `numpy` array, might have to dig a little bit deeper into pydantic issues to see if there's an open thread(if not start one). The alternative is to use `default_factory` argument in `position_` field for `abstract_site.py`. Which is done in #482.
