### ISSUE TITLE
SubTopology Enhancements

### ISSUE THREAD

**Issue by umesh-timalsina** [mosdef-hub/gmso#494]
It might be nice to be able to add the following features to a `Topology`:

1. A `Topology` should be arbitrarily able to contain any number of `Topologies` hence making it truely hierarchical datastructure.
2. You should be able to Flatten Out a `SubTopology` and. Arbitrarily select certain `Sites` and associated `Connections` and `Potentials` as a `SubTopology`.

**Comment by CalCraven** [comment]
I talked to someone that seems fairly experienced in bio simulations. As far as I can tell, there is no unique information that is present based on the residue or molecules of each individual atom. It is just a tag that helps for visualization and data analysis of the trajectory. 

In order to facilitate integration to the platforms that need residue information, it might be helpful to be able to easily tag a particular residue. But that isn't something that needs to be addressed by `subtopology` enhancements in my opinion. I don't think we need the hard encoded hierarchy of `topology` `molecule` `residue` `atom`.

The above enhancements are probably still useful to have. I think the most important aspect would be to allow for a user to take two separate `topologies` and combine them. This would make the two previous `topologies` a `subtopology` that still have some functionality such as being easily selectable. Is there any other functionality we realistically would want?

**Comment by umesh-timalsina** [comment]
We already have a primitive support for tagging `sites`: https://github.com/mosdef-hub/gmso/blob/49217ca8daa6c8b01f6bc667d271a321b6f6f16a/gmso/abc/abstract_site.py#L44-L47. This can be levaraged/improved for the flat structures if so needed.  

On combining topologies front: There are couple of questions:
1. How should we handle the `SubTopololgies` within the `Topologies` that are added themshelves? Should we flatten them out?  This needs to be sorted out.
2. If combining is supported, should splitting be supported as well?
