### ISSUE TITLE
Should checking atom type existence when creating a ForceField be Optional ?

### ISSUE THREAD

**Issue by umesh-timalsina** [mosdef-hub/gmso#497]
It looks like a force field  can contain arbitrary `bond` / `angle` / `dihedral` types even if the atom `types`/`classes` defining the interaction between the `bonds` / `angles` / `dihedrals` do not exist in the `forcefield`. It might be better to get rid of this check or make this check optional at the very least.

Related Issues/ PRs:
Foyer XML Conversion: #402 
GMSO Integration with foyer: https://github.com/mosdef-hub/foyer/pull/358

**Comment by CalCraven** [comment]
So to make sure I'm understanding this correctly, you are saying that a forcefield can contain a bond instance between say `oplsaa_135` and oplsaa_267`, and have all of the proper parameters for this bond. But these atomtypes don't have to be included in the forcefield.

What is the check that you want to get rid of in this case, or make optional?

**Comment by daico007** [comment]
I think this check should be optional and can result in either a warning or an error.

I understand the check is supposed to prevent a connection type to be used incorrectly (to be assigned in a system where we well know that's not gonna use the components atomtypes). However, from the atom typing standpoint, these connection types are harmless (just might be redundant) since we start with assigning atom types, and then connection types. This means those connection types that used non-exist atom types will never be matched. 

So, I think it is reasonable to have the checking default to `True`, but have a switch to turn it off for certain cases.

**Comment by umesh-timalsina** [comment]
Yeah. Currently, we don't allow cases like that in your example. AtomTyping with `foyer` will fail if you happen to have a bond defined between these types/classes that do not exist in the `AtomTypes` section. However, when we (@daico007, @justinGilmer) did some digging into this the error messages from `OpenMM` were not very helpful.

**Comment by daico007** [comment]
Another point of having this check optional is that it would allow some forcefield to have connection parameters (define between atom classes) be defined before the specific atom types got added. I am not sure how useful that gonna be, but just make the process a bit more flexible.

**Comment by umesh-timalsina** [comment]
So, if we are deciding this to be the case, should this be optional? If optional, should this be default behavior?

**Comment by daico007** [comment]
I think the default should still be `True`, since people turning it off should know what they are doing

**Comment by umesh-timalsina** [comment]
Okay. This might be done in the validation step, rather than object creation step with options to disable/enable `AtomType` existence.
