### ISSUE TITLE
Schema validation issue with from_foyer_xml

### ISSUE THREAD

**Issue by zijiewu3** [mosdef-hub/gmso#522]
After converting our `foyer` `ONA` xml file to `gmso` xml using the `from_foyer_xml` function, I found some issues in the XML file. These include:
1. `AtomType` section leaves parameters in the expressions undefined. For example,
![image](https://user-images.githubusercontent.com/46448769/110840948-55f68000-8273-11eb-909d-e1cb9738dc54.png)
If the relevant information is not supplied in the original XML file, I think some default values should be assigned to ensure the XML file passes validation.

2. `ConnectionType` section does not correctly handle `class` against `type`. For example,
![image](https://user-images.githubusercontent.com/46448769/110841304-bab1da80-8273-11eb-9a73-1dc23346fb35.png)
`BB` should be a `class` instead of a `type`.

3. Issue with expression parameters in `ImproperType`. For example,
![image](https://user-images.githubusercontent.com/46448769/110842122-b508c480-8274-11eb-99fb-28a947727945.png)
The parameters in `expression`, `ParametersUnitDef`, and the parameters in individual `DihedralType` do not have matching names.

**Comment by zijiewu3** [comment]
An example of the foyer XML file for the ONA model can be found [here](https://github.com/zijiewu3/forcefield_ona/blob/master/ONA.xml).

**Comment by rsdefever** [comment]
The difference between the expression `k * (1 + cos(n * phi - delta))` and the parameter `n0`, `k0`, `n1`, `k1`, is because periodic multiple dihedrals can be "layered" on top of each other. The way that is handled by the `openmm` XML format is that the first dihedral has parameter values `n0`, `k0`, `delta0`, the second has `n1`, `k1`, `delta1`, the third has `n2`, `k2`, `delta2`, etc. This is clearly not being handled correctly in the conversion from the `openmm/foyer` XML format to the `gmso` XML.

**Comment by daico007** [comment]
GMSO `from_foyer_xml` has been deprecated in favor of being handled by `forcefield_utilities`
