### ISSUE TITLE
GMSO is printing out impropers for ethane-AA

### ISSUE THREAD

**Issue by bc118** [mosdef-hub/gmso#618]
_There are a few options here, likely both:_
- GMSO should utilize an algorithm for improper to determine if they are in  a ring, N-C(=O)C bond, or another case where an improper is likely
- GMSO should only continue with the improper(s) if they are found in the FF file or they are said to ignore them. 

Is there already a fix for this? I may have missed it.

**Comment by daico007** [comment]
Umesh has implemented an option in `gmso.Topology.identify_connections` (or something along that name) that would return only the index of the connections. This will allow us to only create connection objects if we found the types for them. This, though, need to be implemented through the foyer side (since `gmso.general_forcefield.Forcefield.apply()` is where all these things happen).

**Comment by chrisiacovella** [comment]
See: https://github.com/mosdef-hub/foyer/issues/491

This PR should fix the issue: https://github.com/mosdef-hub/foyer/pull/493
